---
- hosts: all
  vars:
    max_clients: 200
  remote_user: root
  tasks:
  - name: Update aide after patching
    command: /usr/sbin/aide --update

  - name: check aide file exists 
    stat: path=aide.db.new.gz
    register: aide_stat

  - name: Move aide to bar
    command: cp -fp aide.db.new.gz aide.db.gz
    when: aide_stat.stat.exists

  - name: Compare aid with current filesystem
    command: /usr/sbin/aide --check
